CREATE TABLE `SCHEDULE` (
    `SCHEID`	INT	AUTO_INCREMENT NOT NULL,
    `NAME`	VARCHAR(255)	NOT NULL,
    `PASSWD`	VARCHAR(255)	NOT NULL,
    `WORK`	VARCHAR(200)	NOT NULL,
    `CREATEDATE`	DATETIME	NOT NULL,
    `MODIFYDATE`	DATETIME	NOT NULL,
    PRIMARY KEY (SCHEID)
);